apiVersion: apps/v1
kind: Deployment
metadata:
  name: nitro-rtp
  namespace: nitro
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  nitro-rtp
  template:
    metadata:
      labels:
        app:  nitro-rtp
    spec:
      imagePullSecrets:
      - name: jfrog-cred
      containers:
      - name:  nitro-rtp
        image: paskou.jfrog.io/nitro-docker-local/nitro:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"
        
