apiVersion: v1
kind: Service
metadata:
  name: nitro-rtp-service
  namespace: nitro
spec:
  selector:
    app: nitro-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
  type: NodePort
